org: kusa1224
app: little-t
service: twitter-callback-handler
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
